# -*- coding: utf-8 -*-
"""point_transformer_seg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hD1OCM4IkR-Vqi4-qqdCEHot8NZt67vq
"""

import torch
import torch.nn as nn
from torch_geometric.nn import PointTransformerConv
from torch_cluster import knn_graph

class PointTransformerSeg(nn.Module):

  def __init__(self, in_channels=3, hidden_dim=64, num_classes=9, k=16):
    super().__init__()
    self.k = k

    self.conv1 = PointTransformerConv(in_channels, hidden_dim)
    self.conv2 = PointTransformerConv(hidden_dim, hidden_dim)
    self.conv3 = PointTransformerConv(hidden_dim, hidden_dim)
    self.fc = nn.Linear(hidden_dim, num_classes)

  def forward(self, x, pos, batch):
      
    # Build knn graph manually
    edge_index = knn_graph(pos, k=self.k, batch=batch, loop=True)

    x = self.conv1(x, pos, edge_index)
    x = self.conv2(x, pos, edge_index)
    x = self.conv3(x, pos, edge_index)
    x = self.fc(x)

    return x