# -*- coding: utf-8 -*-
"""Read.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V4ZLQr_PRTfS7-IrUDtoS_8DNv_lSuIe
"""

from google.colab import drive
drive.mount("/content/MyDrive")

!pip install plyfile

!unzip MyDrive/MyDrive/Toronto_3D.zip -d /content/MyDrive/MyDrive/Toronto_3D

"""# **Read All Attributes (XYZ, RGB, Intensity, Label)**"""

import numpy as np
from plyfile import PlyData

file_path = "/content/MyDrive/MyDrive/Toronto_3D/Toronto_3D/L004.ply"
ply_data = PlyData.read(file_path)
vertex = ply_data['vertex']

xyz = np.vstack([vertex['x'], vertex['y'], vertex['z']])
intensity = np.array(vertex['scalar_Intensity'])
rgb = np.vstack([vertex['red'], vertex['green'], vertex['blue']]).T
label = np.array(vertex['scalar_Label'])

print("XYZ shape:", xyz.shape)
print("Labels unique values:", np.unique(label))

"""# **Save as .npz for ML Pipeline**"""

np.savez("/content/MyDrive/MyDrive/NPZ_LiDAR/test/L004.npz", xyz=xyz, features=np.hstack([intensity[:,None], rgb/255.0]), labels=label)