# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zx72hY0P4hhS49n27oCSdFAXQzhYFzkq
"""

import os,sys
from google.colab import drive

drive.mount('/content/MyDrive')
os.chdir('/content/MyDrive/MyDrive/LiDAR_Project')
sys.path.append(os.getcwd())

!pip install torch-geometric
!pip install torch-cluster

import torch
from torch_geometric.loader import DataLoader
from dataset import LiDARSegDataset
from models.point_transformer_seg import PointTransformerSeg
from utils import visualize_pointcloud

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# -------------------------
# Load Test Dataset
# -------------------------

test_dataset = LiDARSegDataset(root='/content/MyDrive/MyDrive/LiDAR_Project/NPZ_LiDAR', split='test')
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False)

# -------------------------
# Load Trained Model
# -------------------------

model = torch.load('/content/MyDrive/MyDrive/LiDAR_Project/point_transformer_full_model.pth', map_location=device, weights_only=False)
model = model.to(device)
model.eval()

# -----------------------
# Evaluate & visualize
# -----------------------
for idx,data in enumerate(test_loader):
  data = data.to(device)

  # Forward path
  with torch.no_grad():
    out = model(data.x, data.pos, data.batch) #[num_points, num_classes]
    preds = out.argmax(dim=1)

  pos = data.pos.cpu().numpy()
  preds = preds.cpu().numpy()

  # Save visualizations
  os.makedirs('Results', exist_ok=True)
  save_path = f'Results/test_{idx}.png'
  visualize_pointcloud(pos, preds, save_path)

  print(f'Saved visualization: {save_path}')