# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175iki5qWnlv49AaipQ60GAiK8_CWJf0R
"""

from google.colab import drive
drive.mount('/content/MyDrive')

!pip install torch_geometric
!pip install torch-cluster

import os, sys
os.chdir('/content/MyDrive/MyDrive/LiDAR_Project')
sys.path.append(os.getcwd())

import torch
from torch_geometric.loader import DataLoader
from tqdm import tqdm
from models.point_transformer_seg import PointTransformerSeg
from dataset import LiDARSegDataset


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
train_dataset = LiDARSegDataset(root='/content/MyDrive/MyDrive/LiDAR_Project/NPZ_LiDAR', split='train')
val_dataset = LiDARSegDataset(root='/content/MyDrive/MyDrive/LiDAR_Project/NPZ_LiDAR', split='valid')

train_loader = DataLoader(train_dataset, batch_size=1, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=1)

model = PointTransformerSeg(in_channels=4, hidden_dim=64, num_classes=9).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = torch.nn.CrossEntropyLoss()

for epoch in range(150):
  model.train()
  total_loss = 0
  for data in tqdm(train_loader):
    data = data.to(device)
    optimizer.zero_grad()
    out =model(data.x, data.pos, data.batch)
    loss = criterion(out, data.y)
    loss.backward()
    optimizer.step()
    total_loss += loss.item()
  print(f"Epoch: {epoch+1}, Train Loss:{total_loss/len(train_loader):.4f}")
torch.save(model, '/content/MyDrive/MyDrive/LiDAR_Project/point_transformer_full_model.pth')