# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4aA1Zf41LHcm7CT9CmqLW0mQqwU3EnP
"""

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import os

def visualize_pointcloud(pos, labels, save_path):
  fig = plt.figure(figsize=(10, 10))
  ax = fig.add_subplot(111, projection='3d')
  ax.set_xlabel('X', weight='bold')
  ax.set_ylabel('Y', weight='bold')
  ax.set_zlabel('Class Label', weight='bold')
  scatter = ax.scatter(pos[:, 0], pos[:, 1], pos[:, 2], c=labels, cmap= 'tab20', s=1)
  plt.colorbar(scatter)
  if save_path:
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    plt.savefig(save_path)
  plt.show()